import {
  AppThemePack,
  AppThemeId,
  AvatarDecoration,
  ProfileBackground,
  EquipableTitle,
  NameplateEffect,
  ReaderThemePack,
  AdvancedPlayerConfig,
} from '../../types/personalization';

// 1. APP THEME PACKS CATALOG
export const APP_THEME_PACKS: Record<AppThemeId, AppThemePack> = {
  dark_synth: {
    id: 'dark_synth',
    name: 'Dark Synthwave',
    tagline: 'Deep obsidian with neon violet and vivid rose accents',
    description: 'The signature Anzo default dark theme with high-contrast glowing elements.',
    icon: 'sparkles',
    primaryGradient: ['#8B5CF6', '#EC4899'],
    cardGradient: ['#12151F', '#181C2A'],
    unlocked: true,
    requiredLevel: 1,
    colors: {
      background: '#0B0D13',
      card: '#12151F',
      cardHover: '#181C2A',
      surface: '#1A1E2D',
      surfaceLight: '#23283B',
      primary: '#8B5CF6',
      secondary: '#06B6D4',
      accent: '#F43F5E',
      accentOrange: '#F97316',
      textPrimary: '#FFFFFF',
      textSecondary: '#94A3B8',
      textMuted: '#64748B',
      border: '#1E293B',
      borderLight: '#334155',
      glow: 'rgba(139, 92, 246, 0.45)',
      glass: 'rgba(18, 21, 31, 0.85)',
      badgeBg: 'rgba(139, 92, 246, 0.15)',
    },
  },
  oled_pitch: {
    id: 'oled_pitch',
    name: 'OLED Pitch Black',
    tagline: 'True #000000 black for maximum battery savings and infinite contrast',
    description: 'Minimalist pitch dark theme optimized for OLED and AMOLED displays.',
    icon: 'moon',
    primaryGradient: ['#FFFFFF', '#A1A1AA'],
    cardGradient: ['#0A0A0A', '#141414'],
    unlocked: true,
    requiredLevel: 1,
    colors: {
      background: '#000000',
      card: '#0D0D0D',
      cardHover: '#171717',
      surface: '#1A1A1A',
      surfaceLight: '#262626',
      primary: '#FFFFFF',
      secondary: '#E4E4E7',
      accent: '#38BDF8',
      accentOrange: '#FB923C',
      textPrimary: '#FFFFFF',
      textSecondary: '#A1A1AA',
      textMuted: '#71717A',
      border: '#27272A',
      borderLight: '#3F3F46',
      glow: 'rgba(255, 255, 255, 0.25)',
      glass: 'rgba(13, 13, 13, 0.95)',
      badgeBg: 'rgba(255, 255, 255, 0.12)',
    },
  },
  cyberpunk: {
    id: 'cyberpunk',
    name: 'Cyberpunk Neon 2077',
    tagline: 'Electric cyan lasers and fluorescent yellow high-voltage styling',
    description: 'High-energy futuristic Tokyo aesthetic with radiant neon glows.',
    icon: 'flash',
    primaryGradient: ['#00F0FF', '#FFE600'],
    cardGradient: ['#0B111E', '#111B2E'],
    unlocked: true,
    requiredLevel: 10,
    requiredRank: 'D_RANK',
    colors: {
      background: '#050811',
      card: '#0B132B',
      cardHover: '#111F3C',
      surface: '#1C2D54',
      surfaceLight: '#253B6E',
      primary: '#00F0FF',
      secondary: '#FFE600',
      accent: '#FF0055',
      accentOrange: '#FF8800',
      textPrimary: '#E0F7FA',
      textSecondary: '#80DEEA',
      textMuted: '#4DD0E1',
      border: '#00F0FF44',
      borderLight: '#00F0FF88',
      glow: 'rgba(0, 240, 255, 0.6)',
      glass: 'rgba(11, 19, 43, 0.85)',
      badgeBg: 'rgba(0, 240, 255, 0.2)',
    },
  },
  crimson_blood: {
    id: 'crimson_blood',
    name: 'Crimson Blood Moon',
    tagline: 'Demon Slayer Hinokami Kagura blazing scarlet and gold embers',
    description: 'Fiery crimson tones crafted for action anime connoisseurs.',
    icon: 'flame',
    primaryGradient: ['#EF4444', '#F97316'],
    cardGradient: ['#1A0B0E', '#2A1015'],
    unlocked: true,
    requiredLevel: 20,
    requiredRank: 'C_RANK',
    colors: {
      background: '#0D0507',
      card: '#1A0B0E',
      cardHover: '#2A1015',
      surface: '#38161D',
      surfaceLight: '#4A1D27',
      primary: '#EF4444',
      secondary: '#F59E0B',
      accent: '#DC2626',
      accentOrange: '#FB923C',
      textPrimary: '#FEE2E2',
      textSecondary: '#FCA5A5',
      textMuted: '#F87171',
      border: '#7F1D1D',
      borderLight: '#991B1B',
      glow: 'rgba(239, 68, 68, 0.55)',
      glass: 'rgba(26, 11, 14, 0.85)',
      badgeBg: 'rgba(239, 68, 68, 0.2)',
    },
  },
  emerald_matrix: {
    id: 'emerald_matrix',
    name: 'Emerald Matrix',
    tagline: 'Terminal green digital rain and glowing phosphor crystals',
    description: 'Sleek sci-fi hacker palette with calming cybernetic greens.',
    icon: 'code-working',
    primaryGradient: ['#10B981', '#06B6D4'],
    cardGradient: ['#071913', '#0C2820'],
    unlocked: true,
    requiredLevel: 30,
    requiredRank: 'B_RANK',
    colors: {
      background: '#040F0B',
      card: '#071A14',
      cardHover: '#0C2A20',
      surface: '#123D2F',
      surfaceLight: '#18503E',
      primary: '#10B981',
      secondary: '#34D399',
      accent: '#059669',
      accentOrange: '#10B981',
      textPrimary: '#ECFDF5',
      textSecondary: '#A7F3D0',
      textMuted: '#6EE7B7',
      border: '#064E3B',
      borderLight: '#065F46',
      glow: 'rgba(16, 185, 129, 0.5)',
      glass: 'rgba(7, 26, 20, 0.85)',
      badgeBg: 'rgba(16, 185, 129, 0.2)',
    },
  },
  midnight_violet: {
    id: 'midnight_violet',
    name: 'Midnight Shadow Monarch',
    tagline: 'Sung Jinwoo ethereal monarch violet shadow sovereign atmosphere',
    description: 'Mysterious royal purples and dark nebula gradients.',
    icon: 'planet',
    primaryGradient: ['#C084FC', '#818CF8'],
    cardGradient: ['#140D26', '#1E1438'],
    unlocked: true,
    requiredLevel: 45,
    requiredRank: 'A_RANK',
    colors: {
      background: '#090514',
      card: '#130B24',
      cardHover: '#1F123B',
      surface: '#2D1A54',
      surfaceLight: '#3D2470',
      primary: '#C084FC',
      secondary: '#A855F7',
      accent: '#E879F9',
      accentOrange: '#F472B6',
      textPrimary: '#FAF5FF',
      textSecondary: '#E9D5FF',
      textMuted: '#D8B4FE',
      border: '#581C87',
      borderLight: '#6B21A8',
      glow: 'rgba(192, 132, 252, 0.6)',
      glass: 'rgba(19, 11, 36, 0.85)',
      badgeBg: 'rgba(192, 132, 252, 0.22)',
    },
  },
  sunset_gold: {
    id: 'sunset_gold',
    name: 'Sunset Sovereign Gold',
    tagline: 'Imperial gold and radiant sunset amber for National-Rank authorities',
    description: 'Ultra-prestigious gilded theme with warm champagne reflections.',
    icon: 'trophy',
    primaryGradient: ['#F59E0B', '#EF4444'],
    cardGradient: ['#1F1607', '#2E220D'],
    unlocked: true,
    requiredLevel: 60,
    requiredRank: 'S_RANK',
    colors: {
      background: '#120D04',
      card: '#1F1608',
      cardHover: '#2E220F',
      surface: '#423117',
      surfaceLight: '#594320',
      primary: '#F59E0B',
      secondary: '#FCD34D',
      accent: '#FFD700',
      accentOrange: '#F97316',
      textPrimary: '#FFFBEB',
      textSecondary: '#FDE68A',
      textMuted: '#FCD34D',
      border: '#78350F',
      borderLight: '#92400E',
      glow: 'rgba(245, 158, 11, 0.6)',
      glass: 'rgba(31, 22, 8, 0.85)',
      badgeBg: 'rgba(245, 158, 11, 0.2)',
    },
  },
  sakura_bloom: {
    id: 'sakura_bloom',
    name: 'Sakura Petal Bloom',
    tagline: 'Gentle pastel cherry blossoms floating over soft dusk violet',
    description: 'Soothing romantic aesthetic inspired by Spring anime releases.',
    icon: 'flower',
    primaryGradient: ['#F472B6', '#C084FC'],
    cardGradient: ['#1A0F1A', '#281728'],
    unlocked: true,
    requiredLevel: 5,
    colors: {
      background: '#0F0910',
      card: '#1A0F1B',
      cardHover: '#2A1A2C',
      surface: '#3B243E',
      surfaceLight: '#4E3052',
      primary: '#F472B6',
      secondary: '#FDA4AF',
      accent: '#FB7185',
      accentOrange: '#F43F5E',
      textPrimary: '#FFF1F2',
      textSecondary: '#FECDD3',
      textMuted: '#FDA4AF',
      border: '#831843',
      borderLight: '#9D174D',
      glow: 'rgba(244, 114, 182, 0.5)',
      glass: 'rgba(26, 15, 27, 0.85)',
      badgeBg: 'rgba(244, 114, 182, 0.2)',
    },
  },
};

// 2. PROFILE BACKGROUNDS & WALLPAPERS CATALOG
export const PROFILE_BACKGROUNDS: ProfileBackground[] = [
  {
    id: 'bg_shadow_gates',
    name: 'Shadow Sovereign Gates',
    bannerUrl: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?w=1200&auto=format&fit=crop&q=80',
    rarity: 'MYTHIC',
    overlayGradient: ['rgba(9, 5, 20, 0.3)', 'rgba(9, 5, 20, 0.95)'],
    themeAccent: '#C084FC',
    description: 'The ethereal violet dimensional gate where the Shadow Monarch commands his army.',
    unlocked: true,
    requiredLevel: 40,
    requiredRank: 'A_RANK',
  },
  {
    id: 'bg_shibuya_neon',
    name: 'Shibuya Neon Crosswalk',
    bannerUrl: 'https://images.unsplash.com/photo-1503899036084-c55cdd92da26?w=1200&auto=format&fit=crop&q=80',
    rarity: 'EPIC',
    overlayGradient: ['rgba(5, 8, 17, 0.2)', 'rgba(5, 8, 17, 0.95)'],
    themeAccent: '#00F0FF',
    description: 'Electric rain-soaked Tokyo streetscape drenched in glowing cyan and magenta signboards.',
    unlocked: true,
    requiredLevel: 15,
    requiredRank: 'D_RANK',
  },
  {
    id: 'bg_hinokami_mountain',
    name: 'Mount Sagiri Snow & Embers',
    bannerUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=1200&auto=format&fit=crop&q=80',
    rarity: 'LEGENDARY',
    overlayGradient: ['rgba(13, 5, 7, 0.3)', 'rgba(13, 5, 7, 0.95)'],
    themeAccent: '#EF4444',
    description: 'Swirling snowstorm illuminated by blazing red and amber sun-breathing dance embers.',
    unlocked: true,
    requiredLevel: 25,
    requiredRank: 'B_RANK',
  },
  {
    id: 'bg_cyber_metropolis',
    name: 'Neo-Cyber Metropolis',
    bannerUrl: 'https://images.unsplash.com/photo-1514565131-fce0801e5785?w=1200&auto=format&fit=crop&q=80',
    rarity: 'RARE',
    overlayGradient: ['rgba(11, 19, 43, 0.3)', 'rgba(11, 19, 43, 0.95)'],
    themeAccent: '#FFE600',
    description: 'Towering megastructures piercing the foggy cyberpunk clouds of the year 2099.',
    unlocked: true,
    requiredLevel: 5,
  },
  {
    id: 'bg_frieren_garden',
    name: 'Ende Astral Flowered Hills',
    bannerUrl: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=1200&auto=format&fit=crop&q=80',
    rarity: 'EPIC',
    overlayGradient: ['rgba(10, 15, 25, 0.3)', 'rgba(10, 15, 25, 0.95)'],
    themeAccent: '#60A5FA',
    description: 'A thousand-year journey through tranquil turquoise alpine slopes under starlight.',
    unlocked: true,
    requiredLevel: 20,
    requiredRank: 'C_RANK',
  },
  {
    id: 'bg_sefirah_castle',
    name: 'Sefirah Fog of History',
    bannerUrl: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=1200&auto=format&fit=crop&q=80',
    rarity: 'MYTHIC',
    overlayGradient: ['rgba(15, 10, 25, 0.4)', 'rgba(15, 10, 25, 0.95)'],
    themeAccent: '#A855F7',
    description: 'Above the grey fog sits the Divine Court of the Tarot Club Lord of Mysteries.',
    unlocked: false,
    requiredLevel: 75,
    requiredRank: 'NATIONAL_RANK',
  },
  {
    id: 'bg_grand_line_ocean',
    name: 'Grand Line Thousand Sunny',
    bannerUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&auto=format&fit=crop&q=80',
    rarity: 'COMMON',
    overlayGradient: ['rgba(11, 13, 19, 0.3)', 'rgba(11, 13, 19, 0.95)'],
    themeAccent: '#F97316',
    description: 'Sunny seas and boundless adventure towards the Laugh Tale treasure.',
    unlocked: true,
    requiredLevel: 1,
  },
  {
    id: 'bg_celestial_sovereign',
    name: 'Golden Throne of Authorities',
    bannerUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=1200&auto=format&fit=crop&q=80',
    rarity: 'MYTHIC',
    overlayGradient: ['rgba(18, 13, 4, 0.4)', 'rgba(18, 13, 4, 0.95)'],
    themeAccent: '#FFD700',
    description: 'Exclusive gilded palace background reserved for National-Level Authorities.',
    unlocked: false,
    requiredLevel: 80,
    requiredRank: 'NATIONAL_RANK',
  },
];

// 3. AVATAR DECORATIONS & FRAMES CATALOG
export const AVATAR_DECORATIONS: AvatarDecoration[] = [
  {
    id: 'frame_shadow_aura',
    name: 'Shadow Monarch Aura',
    rarity: 'MYTHIC',
    borderColor: '#BD00FF',
    glowColor: 'rgba(189, 0, 255, 0.7)',
    accentColor: '#818CF8',
    particleIcon: '🌌',
    description: 'Swirling ethereal violet shadow flames surrounding your avatar.',
    unlocked: true,
    requiredLevel: 40,
    requiredRank: 'A_RANK',
  },
  {
    id: 'frame_dragon_fire',
    name: 'Inferno Dragon Flame',
    rarity: 'EPIC',
    borderColor: '#FF4D4D',
    glowColor: 'rgba(255, 77, 77, 0.7)',
    accentColor: '#F59E0B',
    particleIcon: '🔥',
    description: 'Blazing crimson fire border inspired by Hinokami Kagura dance.',
    unlocked: true,
    requiredLevel: 25,
    requiredRank: 'B_RANK',
  },
  {
    id: 'frame_neon_cyber',
    name: 'Cyberpunk Laser Grid',
    rarity: 'RARE',
    borderColor: '#00F0FF',
    glowColor: 'rgba(0, 240, 255, 0.7)',
    accentColor: '#FFE600',
    particleIcon: '⚡',
    description: 'Electric cyan neon laser frame with dynamic edge glow.',
    unlocked: true,
    requiredLevel: 10,
    requiredRank: 'D_RANK',
  },
  {
    id: 'frame_sakura_petals',
    name: 'Sakura Blossom Vortex',
    rarity: 'RARE',
    borderColor: '#F472B6',
    glowColor: 'rgba(244, 114, 182, 0.65)',
    accentColor: '#FDA4AF',
    particleIcon: '🌸',
    description: 'Delicate pink cherry blossom petals orbiting in harmony.',
    unlocked: true,
    requiredLevel: 5,
  },
  {
    id: 'frame_void_sovereign',
    name: 'Void Sovereign Eclipse',
    rarity: 'LEGENDARY',
    borderColor: '#A855F7',
    glowColor: 'rgba(168, 85, 247, 0.75)',
    accentColor: '#38BDF8',
    particleIcon: '🔮',
    description: 'Deep cosmic purple ring reflecting distant collapsed supernovas.',
    unlocked: true,
    requiredLevel: 35,
    requiredRank: 'A_RANK',
  },
  {
    id: 'frame_golden_halo',
    name: 'Celestial Sovereign Halo',
    rarity: 'MYTHIC',
    borderColor: '#FFD700',
    glowColor: 'rgba(255, 215, 0, 0.8)',
    accentColor: '#F59E0B',
    particleIcon: '👑',
    description: 'Pure 24k polished golden corona for top guild leaders.',
    unlocked: false,
    requiredLevel: 75,
    requiredRank: 'NATIONAL_RANK',
  },
  {
    id: 'frame_matrix_glitch',
    name: 'Matrix Data Stream',
    rarity: 'EPIC',
    borderColor: '#10B981',
    glowColor: 'rgba(16, 185, 129, 0.7)',
    accentColor: '#34D399',
    particleIcon: '💻',
    description: 'Cascading digital runes encasing the portrait.',
    unlocked: true,
    requiredLevel: 30,
    requiredRank: 'B_RANK',
  },
  {
    id: 'frame_basic_sleek',
    name: 'Polished Titanium',
    rarity: 'COMMON',
    borderColor: '#94A3B8',
    glowColor: 'rgba(148, 163, 184, 0.35)',
    description: 'Clean brushed titanium ring with subtle sheen.',
    unlocked: true,
    requiredLevel: 1,
  },
];

// 4. EQUIPABLE TITLES CATALOG
export const EQUIPABLE_TITLES: EquipableTitle[] = [
  {
    id: 'title_shadow_monarch',
    title: 'Monarch of Shadows',
    lore: 'Master of the infinite undead shadow army who defeated the Monarch of Destruction.',
    rarity: 'MYTHIC',
    color: '#C084FC',
    glowColor: 'rgba(192, 132, 252, 0.8)',
    icon: '⚔️',
    unlocked: true,
    requiredLevel: 50,
    requiredRank: 'S_RANK',
  },
  {
    id: 'title_honored_one',
    title: 'The Honored One',
    lore: '"Throughout Heaven and Earth, I alone am the honored one."',
    rarity: 'LEGENDARY',
    color: '#38BDF8',
    glowColor: 'rgba(56, 189, 248, 0.75)',
    icon: '👁️',
    unlocked: true,
    requiredLevel: 40,
    requiredRank: 'A_RANK',
  },
  {
    id: 'title_supreme_beyonder',
    title: 'Supreme Beyonder',
    lore: 'Sequence 0 of the Fool pathway who wields the powers of the spirit world.',
    rarity: 'MYTHIC',
    color: '#A855F7',
    glowColor: 'rgba(168, 85, 247, 0.8)',
    icon: '🃏',
    unlocked: true,
    requiredLevel: 45,
    requiredRank: 'A_RANK',
  },
  {
    id: 'title_demon_slayer_pillar',
    title: 'Hashira Flame Pillar',
    lore: '"Set your heart ablaze and surpass your limits."',
    rarity: 'EPIC',
    color: '#EF4444',
    glowColor: 'rgba(239, 68, 68, 0.7)',
    icon: '🔥',
    unlocked: true,
    requiredLevel: 25,
    requiredRank: 'B_RANK',
  },
  {
    id: 'title_pirate_king',
    title: 'Pirate King Aspirant',
    lore: 'Sailing fearlessly across the Grand Line chasing ultimate freedom.',
    rarity: 'RARE',
    color: '#F59E0B',
    glowColor: 'rgba(245, 158, 11, 0.65)',
    icon: '🏴‍☠️',
    unlocked: true,
    requiredLevel: 15,
    requiredRank: 'D_RANK',
  },
  {
    id: 'title_frieren_archmage',
    title: 'Archmage of Frieren',
    lore: 'A master mage who defeated the Demon King and collects ordinary folk spells.',
    rarity: 'EPIC',
    color: '#60A5FA',
    glowColor: 'rgba(96, 165, 250, 0.7)',
    icon: '🪄',
    unlocked: true,
    requiredLevel: 30,
    requiredRank: 'B_RANK',
  },
  {
    id: 'title_national_authority',
    title: 'National-Level Authority',
    lore: 'One of the five hunters capable of rivaling entire country-clearing calamity gates.',
    rarity: 'MYTHIC',
    color: '#FFD700',
    glowColor: 'rgba(255, 215, 0, 0.85)',
    icon: '👑',
    unlocked: false,
    requiredLevel: 75,
    requiredRank: 'NATIONAL_RANK',
  },
  {
    id: 'title_limitless_sorcerer',
    title: 'Special Grade Sorcerer',
    lore: 'Possessing bottomless cursed energy reserves and an unyielding domain expansion.',
    rarity: 'LEGENDARY',
    color: '#00F0FF',
    glowColor: 'rgba(0, 240, 255, 0.75)',
    icon: '⚡',
    unlocked: true,
    requiredLevel: 35,
    requiredRank: 'A_RANK',
  },
  {
    id: 'title_void_walker',
    title: 'Void Walker',
    lore: 'Trekking through the abyssal rifts between anime universes.',
    rarity: 'RARE',
    color: '#94A3B8',
    glowColor: 'rgba(148, 163, 184, 0.5)',
    icon: '🌌',
    unlocked: true,
    requiredLevel: 10,
  },
  {
    id: 'title_guild_novice',
    title: 'E-Rank Novice Hunter',
    lore: 'Taking the first awakening steps in the Anzo guild.',
    rarity: 'COMMON',
    color: '#94A3B8',
    glowColor: 'rgba(148, 163, 184, 0.3)',
    icon: '🗡️',
    unlocked: true,
    requiredLevel: 1,
  },
];

// 5. ANIMATED NAMEPLATES CATALOG
export const NAMEPLATE_EFFECTS: NameplateEffect[] = [
  {
    id: 'plate_holographic_cyber',
    name: 'Holographic Cyber Grid',
    style: 'holographic',
    rarity: 'EPIC',
    bgGradient: ['rgba(0, 240, 255, 0.25)', 'rgba(255, 0, 85, 0.2)'],
    borderGlow: '#00F0FF',
    textColor: '#E0F7FA',
    icon: '⚡',
    description: 'Iridescent holographic shimmer with electric cyber neon borders.',
    unlocked: true,
    requiredLevel: 15,
    requiredRank: 'D_RANK',
  },
  {
    id: 'plate_flaming_ember',
    name: 'Blazing Sun Ember',
    style: 'flaming_ember',
    rarity: 'LEGENDARY',
    bgGradient: ['rgba(239, 68, 68, 0.3)', 'rgba(245, 158, 11, 0.2)'],
    borderGlow: '#EF4444',
    textColor: '#FFF1F2',
    icon: '🔥',
    description: 'Dynamic fiery gradient inspired by Demon Slayer flames.',
    unlocked: true,
    requiredLevel: 25,
    requiredRank: 'B_RANK',
  },
  {
    id: 'plate_ethereal_amethyst',
    name: 'Ethereal Shadow Amethyst',
    style: 'ethereal_amethyst',
    rarity: 'MYTHIC',
    bgGradient: ['rgba(192, 132, 252, 0.35)', 'rgba(129, 140, 248, 0.25)'],
    borderGlow: '#C084FC',
    textColor: '#FAF5FF',
    icon: '🌌',
    description: 'Deep violet royal nebula glow with pulsating shadow edges.',
    unlocked: true,
    requiredLevel: 40,
    requiredRank: 'A_RANK',
  },
  {
    id: 'plate_golden_sovereign',
    name: 'Imperial Sovereign Gold',
    style: 'golden_sovereign',
    rarity: 'MYTHIC',
    bgGradient: ['rgba(255, 215, 0, 0.35)', 'rgba(245, 158, 11, 0.25)'],
    borderGlow: '#FFD700',
    textColor: '#FFFBEB',
    icon: '👑',
    description: 'Pure radiant gold shimmer for high-tier guild officers.',
    unlocked: false,
    requiredLevel: 75,
    requiredRank: 'NATIONAL_RANK',
  },
  {
    id: 'plate_cyber_glitch',
    name: 'Matrix Data Stream',
    style: 'cyber_glitch',
    rarity: 'RARE',
    bgGradient: ['rgba(16, 185, 129, 0.25)', 'rgba(6, 182, 212, 0.2)'],
    borderGlow: '#10B981',
    textColor: '#ECFDF5',
    icon: '💻',
    description: 'Green terminal code stream with neon scanlines.',
    unlocked: true,
    requiredLevel: 10,
    requiredRank: 'D_RANK',
  },
  {
    id: 'plate_cosmic_stardust',
    name: 'Cosmic Astral Stardust',
    style: 'cosmic_stardust',
    rarity: 'EPIC',
    bgGradient: ['rgba(96, 165, 250, 0.25)', 'rgba(244, 114, 182, 0.2)'],
    borderGlow: '#60A5FA',
    textColor: '#F0F9FF',
    icon: '✨',
    description: 'Sparkling celestial blue and pink pastel stardust.',
    unlocked: true,
    requiredLevel: 20,
    requiredRank: 'C_RANK',
  },
];

// 6. EXPANDED READING THEMES CATALOG (Novel & Manga)
export const EXPANDED_READER_THEMES: Record<string, ReaderThemePack> = {
  oled: {
    id: 'oled',
    name: 'OLED Pitch Black',
    bg: '#000000',
    text: '#E4E4E7',
    subText: '#A1A1AA',
    hudBg: 'rgba(15, 15, 15, 0.96)',
    border: 'rgba(255, 255, 255, 0.12)',
    accentColor: '#FFFFFF',
  },
  sepia: {
    id: 'sepia',
    name: 'Classic Warm Sepia',
    bg: '#FBF0D9',
    text: '#5F4B32',
    subText: '#8C7355',
    hudBg: '#EFE2C7',
    border: '#DCC8A5',
    accentColor: '#8C7355',
  },
  parchment: {
    id: 'parchment',
    name: 'Vintage Grimoire Parchment',
    bg: '#F4ECD8',
    text: '#3C2F1F',
    subText: '#6A563D',
    hudBg: '#E8DCBF',
    border: '#D3C29F',
    accentColor: '#B45309',
  },
  solarized: {
    id: 'solarized',
    name: 'Solarized Dark Ocean',
    bg: '#002B36',
    text: '#93A1A1',
    subText: '#586E75',
    hudBg: 'rgba(7, 54, 66, 0.96)',
    border: '#268BD2',
    accentColor: '#268BD2',
  },
  dracula: {
    id: 'dracula',
    name: 'Dracula Neon Night',
    bg: '#1E1F29',
    text: '#F8F8F2',
    subText: '#6272A4',
    hudBg: 'rgba(40, 42, 54, 0.96)',
    border: '#BD93F9',
    accentColor: '#FF79C6',
  },
  cyberpunk: {
    id: 'cyberpunk',
    name: 'Cyberpunk Matrix Code',
    bg: '#050A0E',
    text: '#00F0FF',
    subText: '#00838F',
    hudBg: 'rgba(11, 19, 43, 0.96)',
    border: '#00F0FF44',
    accentColor: '#00F0FF',
  },
  forest: {
    id: 'forest',
    name: 'Soft Evergreen Forest',
    bg: '#0D1A14',
    text: '#D1FAE5',
    subText: '#6EE7B7',
    hudBg: 'rgba(6, 32, 22, 0.96)',
    border: '#065F46',
    accentColor: '#10B981',
  },
  dark: {
    id: 'dark',
    name: 'Anzo Synth Dark',
    bg: '#0B0D13',
    text: '#F4F4F5',
    subText: '#94A3B8',
    hudBg: 'rgba(26, 30, 45, 0.96)',
    border: '#1E293B',
    accentColor: '#8B5CF6',
  },
};

export const DEFAULT_ADVANCED_PLAYER_CONFIG: AdvancedPlayerConfig = {
  hudTheme: 'cyberpunk',
  audioEqualizerBoost: 1.0,
  progressBarGlow: true,
  progressBarGlowColor: '#8B5CF6',
  subtitleFontFamily: 'System',
  subtitleTextShadow: true,
  subtitleStrokeWidth: 2,
  smoothVolumeGestures: true,
  highPrecisionScrubbing: true,
};
