import {
  RankTier,
  RankInfo,
  QuestItem,
  CosmeticItem,
  LeaderboardEntry,
  LeaderboardCategory,
} from '../../types/gamification';

export const HUNTER_RANKS: Record<RankTier, RankInfo> = {
  E_RANK: {
    tier: 'E_RANK',
    label: 'E-Rank',
    title: 'E-Rank Novice Hunter',
    icon: '🗡️',
    color: '#94A3B8',
    glowColor: 'rgba(148, 163, 184, 0.3)',
    minLevel: 1,
    perks: ['Basic CinePlayer HUD', 'Standard Community Chat'],
  },
  D_RANK: {
    tier: 'D_RANK',
    label: 'D-Rank',
    title: 'D-Rank Awakened Hunter',
    icon: '🛡️',
    color: '#10B981',
    glowColor: 'rgba(16, 185, 129, 0.4)',
    minLevel: 6,
    perks: ['1080p FHD Playback', 'Custom Subtitle Fonts'],
  },
  C_RANK: {
    tier: 'C_RANK',
    label: 'C-Rank',
    title: 'C-Rank Elite Hunter',
    icon: '⚡',
    color: '#06B6D4',
    glowColor: 'rgba(6, 182, 212, 0.4)',
    minLevel: 12,
    perks: ['Light Novel Voice Narrator', 'Unlock Avatar Frames'],
  },
  B_RANK: {
    tier: 'B_RANK',
    label: 'B-Rank',
    title: 'B-Rank Guild Officer',
    icon: '🔮',
    color: '#3B82F6',
    glowColor: 'rgba(59, 130, 246, 0.4)',
    minLevel: 22,
    perks: ['Manga Offline Preloading', 'Profile Theme Customizer'],
  },
  A_RANK: {
    tier: 'A_RANK',
    label: 'A-Rank',
    title: 'A-Rank Raid Commander',
    icon: '🔥',
    color: '#8B5CF6',
    glowColor: 'rgba(139, 92, 246, 0.45)',
    minLevel: 35,
    perks: ['Cyberpunk CinePlayer HUD', 'Priority Stream Routing'],
  },
  S_RANK: {
    tier: 'S_RANK',
    label: 'S-Rank',
    title: 'S-Rank National Asset',
    icon: '⚔️',
    color: '#F43F5E',
    glowColor: 'rgba(244, 63, 94, 0.5)',
    minLevel: 50,
    perks: ['Glowing Post Shader', 'VIP Chat Badges', '4K Ultra HDR'],
  },
  NATIONAL_RANK: {
    tier: 'NATIONAL_RANK',
    label: 'National Level',
    title: 'National-Level Authority',
    icon: '👑',
    color: '#FFD700',
    glowColor: 'rgba(255, 215, 0, 0.55)',
    minLevel: 75,
    perks: ['Golden Avatar Frame', 'Unlimited Stream Downloads', 'Exclusive Beta Feeds'],
  },
  MONARCH: {
    tier: 'MONARCH',
    label: 'Shadow Monarch',
    title: 'Monarch of Shadows ⚔️',
    icon: '🌌',
    color: '#C084FC',
    glowColor: 'rgba(192, 132, 252, 0.7)',
    minLevel: 100,
    perks: ['Shadow Aura Particle Effect', 'Owner Tier Privileges', 'Infinite Prestige'],
  },
};

export function calculateExpForLevel(level: number): number {
  // Quadratic XP formula: Level 1 = 150, Level 10 = 1500, Level 50 = 7500
  return Math.floor(level * 150 + 100);
}

export function getRankForLevel(level: number): RankInfo {
  if (level >= 100) return HUNTER_RANKS.MONARCH;
  if (level >= 75) return HUNTER_RANKS.NATIONAL_RANK;
  if (level >= 50) return HUNTER_RANKS.S_RANK;
  if (level >= 35) return HUNTER_RANKS.A_RANK;
  if (level >= 22) return HUNTER_RANKS.B_RANK;
  if (level >= 12) return HUNTER_RANKS.C_RANK;
  if (level >= 6) return HUNTER_RANKS.D_RANK;
  return HUNTER_RANKS.E_RANK;
}

export const INITIAL_DAILY_QUESTS: QuestItem[] = [
  {
    id: 'quest_watch_episodes',
    title: 'Daily Binge Watcher',
    description: 'Watch at least 2 anime episodes on CinePlayer',
    expReward: 100,
    icon: 'play-circle',
    type: 'DAILY',
    current: 1,
    target: 2,
    completed: false,
    claimed: false,
  },
  {
    id: 'quest_read_manga',
    title: 'Manga Page Turner',
    description: 'Read 3 chapters of any manga or light novel',
    expReward: 80,
    icon: 'book',
    type: 'DAILY',
    current: 3,
    target: 3,
    completed: true,
    claimed: false,
  },
  {
    id: 'quest_community_post',
    title: 'Voice of the Guild',
    description: 'Drop a hype comment or reaction in Anzo Community',
    expReward: 50,
    icon: 'chatbubble-ellipses',
    type: 'DAILY',
    current: 1,
    target: 1,
    completed: true,
    claimed: false,
  },
  {
    id: 'quest_weekly_series',
    title: 'Season Finisher',
    description: 'Complete 1 entire anime season or arc',
    expReward: 350,
    icon: 'trophy',
    type: 'WEEKLY',
    current: 0,
    target: 1,
    completed: false,
    claimed: false,
  },
];

export const INITIAL_COSMETICS_CATALOG: CosmeticItem[] = [
  {
    id: 'frame_shadow_aura',
    name: 'Shadow Monarch Aura',
    type: 'AVATAR_FRAME',
    description: 'Swirling ethereal violet shadow flames surrounding your avatar.',
    borderColor: '#BD00FF',
    glowColor: 'rgba(189, 0, 255, 0.6)',
    requiredLevel: 40,
    requiredRank: 'A_RANK',
    unlocked: true,
    isEquipped: true,
  },
  {
    id: 'frame_dragon_fire',
    name: 'Inferno Dragon Flame',
    type: 'AVATAR_FRAME',
    description: 'Blazing crimson fire border inspired by Demon Slayer Hinokami.',
    borderColor: '#FF4D4D',
    glowColor: 'rgba(255, 77, 77, 0.6)',
    requiredLevel: 25,
    requiredRank: 'B_RANK',
    unlocked: true,
    isEquipped: false,
  },
  {
    id: 'frame_neon_cyber',
    name: 'Cyberpunk Grid',
    type: 'AVATAR_FRAME',
    description: 'Electric cyan neon laser frame with dynamic edge glow.',
    borderColor: '#00F0FF',
    glowColor: 'rgba(0, 240, 255, 0.6)',
    requiredLevel: 10,
    requiredRank: 'D_RANK',
    unlocked: true,
    isEquipped: false,
  },
  {
    id: 'theme_oled_pitch',
    name: 'OLED Pitch Black',
    type: 'PROFILE_THEME',
    description: 'Pure obsidian dark mode card styling.',
    requiredLevel: 1,
    unlocked: true,
    isEquipped: true,
  },
  {
    id: 'theme_neon_purple',
    name: 'Neon Tokyo Synth',
    type: 'PROFILE_THEME',
    description: 'Vibrant neon purple and hot pink glassmorphic gradient.',
    requiredLevel: 30,
    requiredRank: 'B_RANK',
    unlocked: true,
    isEquipped: false,
  },
  {
    id: 'effect_golden_glow',
    name: 'National Authority Glow',
    type: 'NAME_EFFECT',
    description: 'Shimmering gold text animation for your username.',
    borderColor: '#FFD700',
    glowColor: 'rgba(255, 215, 0, 0.7)',
    requiredLevel: 75,
    requiredRank: 'NATIONAL_RANK',
    unlocked: false,
    isEquipped: false,
  },
];

export const INITIAL_LEADERBOARD_ENTRIES: LeaderboardEntry[] = [
  {
    rankPosition: 1,
    userId: 'user_anzo_owner',
    username: 'ShadowMonarch',
    displayName: 'Sung Jinwoo 👑',
    avatar: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?w=400&auto=format&fit=crop&q=80',
    userRole: 'OWNER',
    rankTag: HUNTER_RANKS.A_RANK,
    score: 8420,
    scoreLabel: '8,420 XP',
    isCurrentUser: true,
    equippedFrame: INITIAL_COSMETICS_CATALOG[0],
  },
  {
    rankPosition: 2,
    userId: 'user_admin_satoru',
    username: 'GojoHonored',
    displayName: 'Gojo Satoru 🛡️',
    avatar: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=400&auto=format&fit=crop&q=80',
    userRole: 'ADMIN',
    rankTag: HUNTER_RANKS.A_RANK,
    score: 7950,
    scoreLabel: '7,950 XP',
    equippedFrame: INITIAL_COSMETICS_CATALOG[2],
  },
  {
    rankPosition: 3,
    userId: 'user_vip_eren',
    username: 'TitanFreedom',
    displayName: 'Eren Yeager ⭐',
    avatar: 'https://images.unsplash.com/photo-1563089145-599997674d42?w=400&auto=format&fit=crop&q=80',
    userRole: 'VIP',
    rankTag: HUNTER_RANKS.B_RANK,
    score: 5820,
    scoreLabel: '5,820 XP',
    equippedFrame: INITIAL_COSMETICS_CATALOG[1],
  },
  {
    rankPosition: 4,
    userId: 'user_luffy_pirate',
    username: 'StrawHatNika',
    displayName: 'Monkey D. Luffy',
    avatar: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=400&auto=format&fit=crop&q=80',
    userRole: 'MEMBER',
    rankTag: HUNTER_RANKS.B_RANK,
    score: 4910,
    scoreLabel: '4,910 XP',
  },
  {
    rankPosition: 5,
    userId: 'user_frieren_mage',
    username: 'FrierenMage',
    displayName: 'Frieren',
    avatar: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=400&auto=format&fit=crop&q=80',
    userRole: 'CREATOR',
    rankTag: HUNTER_RANKS.C_RANK,
    score: 3640,
    scoreLabel: '3,640 XP',
  },
];
