import {
  MediaReview,
  PublicCollection,
  UserRecommendation,
  DiscussionThread,
} from '../../types/community';

export const INITIAL_DISCUSSION_THREADS: DiscussionThread[] = [
  {
    id: 'thread_solo_ep12',
    mediaId: 151807,
    mediaType: 'ANIME',
    mediaTitle: 'Solo Leveling',
    unitLabel: 'Episode 12 (Season Finale)',
    threadTitle: 'Arise: The Monarch Awakens in 4K',
    author: {
      id: 'usr_jinwoo_shadow',
      username: 'ShadowMonarch',
      displayName: 'Sung Jinwoo 👑',
      avatar: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?w=200&auto=format&fit=crop&q=80',
      role: 'OWNER',
    },
    content: 'The animation for the Job Change quest and Igris summoning exceeded all expectations! What did everyone think of the post-credits Jeju Island setup?',
    isSpoiler: true,
    isLocked: false,
    replyCount: 14,
    replies: [
      {
        id: 'reply_th_1',
        postId: 'thread_solo_ep12',
        author: {
          id: 'usr_gojo_satoru',
          username: 'LimitlessGojo',
          displayName: 'Gojo Satoru 🛡️',
          avatar: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=200&auto=format&fit=crop&q=80',
          role: 'ADMIN',
          badges: [],
        },
        content: 'Sawano Hiroyuki OST drop when he said "Arise" gave me pure goosebumps!',
        timestamp: '1h ago',
        reactions: { '🔥': ['usr_jinwoo_shadow'] },
      },
    ],
    createdAt: '2h ago',
  },
  {
    id: 'thread_jjk_ch271',
    mediaId: 'jujutsu_kaisen_manga',
    mediaType: 'MANGA',
    mediaTitle: 'Jujutsu Kaisen',
    unitLabel: 'Chapter 271 (Final Chapter)',
    threadTitle: 'The End of an Era: Series Finale Discussion',
    author: {
      id: 'usr_gojo_satoru',
      username: 'LimitlessGojo',
      displayName: 'Gojo Satoru 🛡️',
      avatar: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=200&auto=format&fit=crop&q=80',
      role: 'ADMIN',
    },
    content: '6 years of Jujutsu Kaisen concludes today. Share your final thoughts on the trio and the legacy of Jujutsu High.',
    isSpoiler: true,
    isLocked: false,
    replyCount: 28,
    replies: [],
    createdAt: '5h ago',
  },
  {
    id: 'thread_shadow_vol4',
    mediaId: 'shadow_slave_novel',
    mediaType: 'NOVEL',
    mediaTitle: 'Shadow Slave',
    unitLabel: 'Third Nightmare Finale',
    threadTitle: 'The Tomb of Ariel & The Estuary Theories',
    author: {
      id: 'usr_sunny_shadow',
      username: 'LostFromLight',
      displayName: 'Sunny 🗡️',
      avatar: 'https://images.unsplash.com/photo-1618336753974-aae8e04506aa?w=200&auto=format&fit=crop&q=80',
      role: 'VIP',
    },
    content: 'Guiltythree cooked something truly extraordinary in the estuary. The concept of the loop is mindblowing.',
    isSpoiler: true,
    isLocked: false,
    replyCount: 19,
    replies: [],
    createdAt: '1d ago',
  },
];

export const INITIAL_REVIEWS: MediaReview[] = [
  {
    id: 'rev_solo_1',
    mediaId: 151807,
    mediaType: 'ANIME',
    mediaTitle: 'Solo Leveling',
    mediaCover: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?w=600&auto=format&fit=crop&q=80',
    author: {
      id: 'usr_critic_master',
      username: 'AnimeOracle',
      displayName: 'Oracle Reviewer ⭐',
      avatar: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=200&auto=format&fit=crop&q=80',
      role: 'VIP',
    },
    overallScore: 9.5,
    storyScore: 9.0,
    artScore: 10.0,
    soundScore: 9.8,
    characterScore: 9.2,
    reviewTitle: 'A Masterclass in Hype, Soundtrack & Visual Execution',
    reviewBody: 'A-1 Pictures delivered one of the greatest manhwa adaptations ever produced. The fluid combat choreography, combined with Sawano Hiroyuki’s godly choral orchestration, elevates every single dungeon fight.',
    containsSpoilers: false,
    helpfulCount: 42,
    helpfulUserIds: ['usr_jinwoo_shadow', 'usr_gojo_satoru'],
    createdAt: 'Yesterday',
  },
  {
    id: 'rev_lotm_1',
    mediaId: 'lotm_novel',
    mediaType: 'NOVEL',
    mediaTitle: 'Lord of the Mysteries',
    mediaCover: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?w=600&auto=format&fit=crop&q=80',
    author: {
      id: 'usr_tarot_club',
      username: 'FoolDevotee',
      displayName: 'Mr. Fool 🎭',
      avatar: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?w=200&auto=format&fit=crop&q=80',
      role: 'CREATOR',
    },
    overallScore: 10.0,
    storyScore: 10.0,
    artScore: 9.5,
    soundScore: 9.0,
    characterScore: 10.0,
    reviewTitle: 'The Pinnacle of Victorian Steampunk Fantasy & Mystery',
    reviewBody: 'The potion pathway system, the high-stakes mysticism, and Klein Moretti’s meticulous progression make this novel an untouchable masterpiece of modern web literature.',
    containsSpoilers: false,
    helpfulCount: 78,
    helpfulUserIds: ['usr_jinwoo_shadow'],
    createdAt: '3 days ago',
  },
];

export const INITIAL_PUBLIC_COLLECTIONS: PublicCollection[] = [
  {
    id: 'col_dark_fantasy',
    title: 'Top Tier Dark Fantasy & OP Protagonists',
    description: 'Curated list of gripping anime, manhwa, and web novels with ruthless world-building and god-level power escalation.',
    coverUrl: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?w=600&auto=format&fit=crop&q=80',
    creator: {
      id: 'usr_jinwoo_shadow',
      username: 'ShadowMonarch',
      displayName: 'Sung Jinwoo 👑',
      avatar: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?w=200&auto=format&fit=crop&q=80',
      role: 'OWNER',
    },
    items: [
      {
        id: 151807,
        mediaType: 'ANIME',
        title: 'Solo Leveling',
        coverUrl: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?w=600&auto=format&fit=crop&q=80',
        note: 'Best modern necromancer fantasy',
      },
      {
        id: 'jujutsu_kaisen_manga',
        mediaType: 'MANGA',
        title: 'Jujutsu Kaisen',
        coverUrl: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=600&auto=format&fit=crop&q=80',
        note: 'Intense sorcery and curses',
      },
      {
        id: 'shadow_slave_novel',
        mediaType: 'NOVEL',
        title: 'Shadow Slave',
        coverUrl: 'https://images.unsplash.com/photo-1618336753974-aae8e04506aa?w=600&auto=format&fit=crop&q=80',
        note: 'Nightmare spell & survival masterclass',
      },
      {
        id: 'lotm_novel',
        mediaType: 'NOVEL',
        title: 'Lord of the Mysteries',
        coverUrl: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?w=600&auto=format&fit=crop&q=80',
        note: 'Victorian occult & Beyonder pathways',
      },
    ],
    likesCount: 142,
    likedUserIds: ['usr_gojo_satoru'],
    tags: ['Dark Fantasy', 'OP Protagonist', 'Top Rated'],
    isPublic: true,
    createdAt: '2 days ago',
  },
  {
    id: 'col_starter_isekai',
    title: 'Peak Isekai & Reincarnation Starter Pack',
    description: 'The most immersive other-world fantasy series with top notch world construction.',
    coverUrl: 'https://images.unsplash.com/photo-1563089145-599997674d42?w=600&auto=format&fit=crop&q=80',
    creator: {
      id: 'usr_gojo_satoru',
      username: 'LimitlessGojo',
      displayName: 'Gojo Satoru 🛡️',
      avatar: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=200&auto=format&fit=crop&q=80',
      role: 'ADMIN',
    },
    items: [
      {
        id: 21127,
        mediaType: 'ANIME',
        title: 'Overlord',
        coverUrl: 'https://images.unsplash.com/photo-1563089145-599997674d42?w=600&auto=format&fit=crop&q=80',
      },
      {
        id: 'overlord_novel',
        mediaType: 'NOVEL',
        title: 'Overlord (Light Novel)',
        coverUrl: 'https://images.unsplash.com/photo-1563089145-599997674d42?w=600&auto=format&fit=crop&q=80',
      },
    ],
    likesCount: 89,
    likedUserIds: [],
    tags: ['Isekai', 'Overlord', 'Fantasy'],
    isPublic: true,
    createdAt: '4 days ago',
  },
];

export const INITIAL_USER_RECOMMENDATIONS: UserRecommendation[] = [
  {
    id: 'rec_1',
    author: {
      id: 'usr_jinwoo_shadow',
      username: 'ShadowMonarch',
      displayName: 'Sung Jinwoo 👑',
      avatar: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?w=200&auto=format&fit=crop&q=80',
      role: 'OWNER',
    },
    sourceMedia: {
      id: 151807,
      mediaType: 'ANIME',
      title: 'Solo Leveling',
      coverUrl: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?w=600&auto=format&fit=crop&q=80',
    },
    targetMedia: {
      id: 'shadow_slave_novel',
      mediaType: 'NOVEL',
      title: 'Shadow Slave (Novel)',
      coverUrl: 'https://images.unsplash.com/photo-1618336753974-aae8e04506aa?w=600&auto=format&fit=crop&q=80',
    },
    reason: 'If you loved Sung Jinwoo rising from weak hunter to shadow monarch, Sunny’s treacherous journey through the Nightmare Spell has the exact same exhilarating dopamine loop with even deeper psychological stakes.',
    helpfulCount: 56,
    helpfulUserIds: ['usr_gojo_satoru'],
    createdAt: '1 day ago',
  },
  {
    id: 'rec_2',
    author: {
      id: 'usr_gojo_satoru',
      username: 'LimitlessGojo',
      displayName: 'Gojo Satoru 🛡️',
      avatar: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=200&auto=format&fit=crop&q=80',
      role: 'ADMIN',
    },
    sourceMedia: {
      id: 113415,
      mediaType: 'ANIME',
      title: 'Jujutsu Kaisen',
      coverUrl: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=600&auto=format&fit=crop&q=80',
    },
    targetMedia: {
      id: 'chainsaw_man_manga',
      mediaType: 'MANGA',
      title: 'Chainsaw Man (Manga)',
      coverUrl: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=600&auto=format&fit=crop&q=80',
    },
    reason: 'Both explore dark, chaotic supernatural worlds with demons/curses and unapologetically high-octane battle set-pieces.',
    helpfulCount: 34,
    helpfulUserIds: [],
    createdAt: '3 days ago',
  },
];
