import { CommunityPost, ChatRoom, ChatMessage, UserProfile, UserRole, UserBadge } from '../../types/community';

export const USER_ROLE_CONFIG: Record<
  UserRole,
  { label: string; icon: string; color: string; bg: string; border: string; glow: string }
> = {
  OWNER: {
    label: 'OWNER',
    icon: '👑',
    color: '#FFD700',
    bg: 'rgba(255, 215, 0, 0.15)',
    border: '#FFD700',
    glow: 'rgba(255, 215, 0, 0.4)',
  },
  ADMIN: {
    label: 'ADMIN',
    icon: '🛡️',
    color: '#FF4D4D',
    bg: 'rgba(255, 77, 77, 0.15)',
    border: '#FF4D4D',
    glow: 'rgba(255, 77, 77, 0.4)',
  },
  MODERATOR: {
    label: 'MOD',
    icon: '⚔️',
    color: '#00F0FF',
    bg: 'rgba(0, 240, 255, 0.15)',
    border: '#00F0FF',
    glow: 'rgba(0, 240, 255, 0.4)',
  },
  VIP: {
    label: 'VIP',
    icon: '⭐',
    color: '#BD00FF',
    bg: 'rgba(189, 0, 255, 0.15)',
    border: '#BD00FF',
    glow: 'rgba(189, 0, 255, 0.4)',
  },
  CREATOR: {
    label: 'CREATOR',
    icon: '🎨',
    color: '#00FF66',
    bg: 'rgba(0, 255, 102, 0.15)',
    border: '#00FF66',
    glow: 'rgba(0, 255, 102, 0.4)',
  },
  MEMBER: {
    label: 'MEMBER',
    icon: '🌟',
    color: '#8E8E93',
    bg: 'rgba(142, 142, 147, 0.12)',
    border: '#3A3A3C',
    glow: 'transparent',
  },
};

export const AVAILABLE_BADGES: UserBadge[] = [
  {
    id: 'badge_founder',
    label: 'Founder',
    icon: '🏆',
    color: '#FFD700',
    description: 'Joined during the Alpha Launch of Anzo Community',
  },
  {
    id: 'badge_speed_reader',
    label: 'Speed Reader',
    icon: '⚡',
    color: '#00F0FF',
    description: 'Completed over 500 manga & light novel chapters',
  },
  {
    id: 'badge_otaku_master',
    label: 'Otaku Master',
    icon: '🔥',
    color: '#FF007A',
    description: 'Watched over 1,000 anime episodes on CinePlayer',
  },
  {
    id: 'badge_top_critic',
    label: 'Top Critic',
    icon: '✍️',
    color: '#BD00FF',
    description: 'Published 20+ verified community reviews & recommendations',
  },
];

export const CURRENT_LOGGED_USER: UserProfile = {
  id: 'user_anzo_owner',
  username: 'ShadowMonarch',
  displayName: 'Sung Jinwoo 👑',
  avatar: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?w=400&auto=format&fit=crop&q=80',
  bannerUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=1200&auto=format&fit=crop&q=80',
  bio: 'Shadow Monarch. Solo Leveling enthusiasts & Lead Developer of Anzo CinePlayer.',
  customStatus: 'Arise... ⚔️',
  role: 'OWNER',
  badges: AVAILABLE_BADGES,
  level: 42,
  xp: 8420,
  joinedDate: 'January 2026',
  followersCount: 1250,
  followingCount: 140,
  favoriteAnime: [
    {
      id: '151807',
      title: 'Solo Leveling',
      coverUrl: 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx151807-33faSWhQS2mC.jpg',
      rating: 9.8,
    },
    {
      id: '113415',
      title: 'Jujutsu Kaisen',
      coverUrl: 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx113415-bbBWj4pTvEBJ.jpg',
      rating: 9.6,
    },
    {
      id: '16498',
      title: 'Attack on Titan',
      coverUrl: 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx16498-m5ZMNScxmJoF.png',
      rating: 9.9,
    },
  ],
  activities: [
    {
      id: 'act_1',
      type: 'WATCHED_EPISODE',
      title: 'Watched Solo Leveling Episode 12',
      subtitle: 'Finished Season 1 Finale in 4K HDR',
      coverUrl: 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx151807-33faSWhQS2mC.jpg',
      rating: 10,
      timestamp: '15m ago',
    },
    {
      id: 'act_2',
      type: 'READ_CHAPTER',
      title: 'Read Shadow Slave Chapter 1850',
      subtitle: 'Reached the Third Nightmare climax',
      timestamp: '2h ago',
    },
  ],
  isOnline: true,
};

export const INITIAL_COMMUNITY_POSTS: CommunityPost[] = [
  {
    id: 'post_pinned_announcement',
    author: {
      id: 'user_anzo_owner',
      username: 'ShadowMonarch',
      displayName: 'Sung Jinwoo 👑',
      avatar: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?w=400&auto=format&fit=crop&q=80',
      role: 'OWNER',
      badges: [AVAILABLE_BADGES[0], AVAILABLE_BADGES[1]],
    },
    content: '🎉 **Welcome to Anzo Community!** \n\nDiscuss your favorite episodes, share anime recommendations, live-chat with members, drop hype GIFs, and customize your profile badges. Be respectful and use the spoiler tag for plot reveals!',
    isPinned: true,
    tags: ['Announcement', 'Anzo', 'Community'],
    timestamp: 'Just now',
    likesCount: 142,
    reactions: {
      '👑': ['user_1', 'user_2', 'user_3', 'user_anzo_owner'],
      '🔥': ['user_4', 'user_5', 'user_6'],
      '❤️': ['user_7', 'user_8'],
    },
    replyCount: 3,
    replies: [
      {
        id: 'reply_1',
        postId: 'post_pinned_announcement',
        author: {
          id: 'user_admin_satoru',
          username: 'GojoHonored',
          displayName: 'Gojo Satoru 🛡️',
          avatar: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=400&auto=format&fit=crop&q=80',
          role: 'ADMIN',
          badges: [AVAILABLE_BADGES[0]],
        },
        content: '@ShadowMonarch The new CinePlayer HUD and Manga Reader look phenomenal! Let\'s gooo! 🔥',
        replyToUser: 'ShadowMonarch',
        timestamp: '5m ago',
        reactions: { '🔥': ['user_anzo_owner', 'user_vip_eren'] },
      },
      {
        id: 'reply_2',
        postId: 'post_pinned_announcement',
        author: {
          id: 'user_vip_eren',
          username: 'TitanFreedom',
          displayName: 'Eren Yeager ⭐',
          avatar: 'https://images.unsplash.com/photo-1563089145-599997674d42?w=400&auto=format&fit=crop&q=80',
          role: 'VIP',
          badges: [AVAILABLE_BADGES[2]],
        },
        content: 'Tatacaw! Loving the direct server switches and offline novel sync.',
        timestamp: '3m ago',
        reactions: { '👏': ['user_admin_satoru'] },
      },
    ],
  },
  {
    id: 'post_solo_leveling_rec',
    author: {
      id: 'user_admin_satoru',
      username: 'GojoHonored',
      displayName: 'Gojo Satoru 🛡️',
      avatar: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=400&auto=format&fit=crop&q=80',
      role: 'ADMIN',
      badges: [AVAILABLE_BADGES[0], AVAILABLE_BADGES[3]],
    },
    content: 'If you loved Jujutsu Kaisen or Bleach, you NEED to watch **Solo Leveling**. The sound design and Hiroyuki Sawano score during the Igris battle gave me absolute chills!',
    gifUrl: 'https://media.giphy.com/media/UgV8Y7bDxsZDCP057i/giphy.gif',
    attachedAnime: {
      id: '151807',
      title: 'Solo Leveling',
      coverUrl: 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx151807-33faSWhQS2mC.jpg',
      rating: 9.8,
      episodes: 12,
      genre: ['Action', 'Fantasy', 'Supernatural'],
    },
    tags: ['Recommendation', 'SoloLeveling', 'Hype'],
    timestamp: '25m ago',
    likesCount: 88,
    reactions: {
      '🔥': ['user_1', 'user_3', 'user_anzo_owner'],
      '❤️': ['user_5', 'user_7'],
      '👑': ['user_2'],
    },
    replyCount: 1,
    replies: [
      {
        id: 'reply_3',
        postId: 'post_solo_leveling_rec',
        author: {
          id: 'user_anzo_owner',
          username: 'ShadowMonarch',
          displayName: 'Sung Jinwoo 👑',
          avatar: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?w=400&auto=format&fit=crop&q=80',
          role: 'OWNER',
          badges: AVAILABLE_BADGES,
        },
        content: '@GojoHonored "Arise" scene in 4K HDR was peak cinema! ⚔️',
        replyToUser: 'GojoHonored',
        timestamp: '18m ago',
        reactions: { '👑': ['user_admin_satoru'] },
      },
    ],
  },
  {
    id: 'post_spoilers_aot',
    author: {
      id: 'user_vip_eren',
      username: 'TitanFreedom',
      displayName: 'Eren Yeager ⭐',
      avatar: 'https://images.unsplash.com/photo-1563089145-599997674d42?w=400&auto=format&fit=crop&q=80',
      role: 'VIP',
      badges: [AVAILABLE_BADGES[2]],
    },
    content: 'The Rumbling sequence and Paths conversation with Armin in the final special completely recontextualized the entire tragedy of Paradis.',
    isSpoiler: true,
    attachedAnime: {
      id: '16498',
      title: 'Attack on Titan Final Season',
      coverUrl: 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx16498-m5ZMNScxmJoF.png',
      rating: 9.9,
    },
    tags: ['Discussion', 'AttackOnTitan', 'Theory'],
    timestamp: '1h ago',
    likesCount: 54,
    reactions: {
      '😱': ['user_1', 'user_4'],
      '💀': ['user_2', 'user_8'],
    },
    replyCount: 0,
    replies: [],
  },
];

export const INITIAL_CHAT_ROOMS: ChatRoom[] = [
  {
    id: 'room_global_lounge',
    name: '#global-lounge',
    topic: 'General anime, manga & light novel chatter 💬',
    type: 'GLOBAL',
    icon: 'globe-outline',
    activeUsersCount: 342,
  },
  {
    id: 'room_episode_live',
    name: '#episode-live-chat',
    topic: 'Live reactions to currently airing seasonal anime ⚡',
    type: 'EPISODE_LIVE',
    icon: 'tv-outline',
    activeUsersCount: 189,
  },
  {
    id: 'room_manga_spoilers',
    name: '#manga-spoilers',
    topic: 'Raw scans, theories & latest chapter discussions 📖',
    type: 'MANGA_SPOILERS',
    icon: 'book-outline',
    activeUsersCount: 95,
  },
];

export const INITIAL_CHAT_MESSAGES: Record<string, ChatMessage[]> = {
  room_global_lounge: [
    {
      id: 'msg_1',
      roomId: 'room_global_lounge',
      author: {
        id: 'user_admin_satoru',
        username: 'GojoHonored',
        displayName: 'Gojo Satoru 🛡️',
        avatar: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=400&auto=format&fit=crop&q=80',
        role: 'ADMIN',
      },
      content: 'Who else is waiting for Jujutsu Kaisen Culling Game arc?! 🤞',
      timestamp: '12:45 PM',
      reactions: { '🔥': ['user_anzo_owner', 'user_vip_eren'] },
    },
    {
      id: 'msg_2',
      roomId: 'room_global_lounge',
      author: {
        id: 'user_anzo_owner',
        username: 'ShadowMonarch',
        displayName: 'Sung Jinwoo 👑',
        avatar: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?w=400&auto=format&fit=crop&q=80',
        role: 'OWNER',
      },
      content: 'MAPPA is cooking something extraordinary for that season!',
      gifUrl: 'https://media.giphy.com/media/4lu5FuhtrbaOQgKN57/giphy.gif',
      timestamp: '12:48 PM',
      reactions: { '👑': ['user_admin_satoru'] },
    },
  ],
  room_episode_live: [
    {
      id: 'msg_3',
      roomId: 'room_episode_live',
      author: {
        id: 'user_vip_eren',
        username: 'TitanFreedom',
        displayName: 'Eren Yeager ⭐',
        avatar: 'https://images.unsplash.com/photo-1563089145-599997674d42?w=400&auto=format&fit=crop&q=80',
        role: 'VIP',
      },
      content: 'Episode 10 animation budget just broke the internet!',
      timestamp: '1:02 PM',
      reactions: { '😱': ['user_anzo_owner'] },
    },
  ],
  room_manga_spoilers: [
    {
      id: 'msg_4',
      roomId: 'room_manga_spoilers',
      author: {
        id: 'user_admin_satoru',
        username: 'GojoHonored',
        displayName: 'Gojo Satoru 🛡️',
        avatar: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=400&auto=format&fit=crop&q=80',
        role: 'ADMIN',
      },
      content: 'Check out the new chapter translations on the Manga tab!',
      timestamp: '11:15 AM',
      reactions: { '👏': ['user_anzo_owner'] },
    },
  ],
};
